site_name: RuinGuard
repo_url: https://github.com/SayuMains/RuinGuard
theme:
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: brown
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: brown
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
