site_name: RuinGuard
repo_url: https://github.com/SayuMains/RuinGuard
theme:
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: orange
    accent: yellow
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
markdown_extensions:
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      anchorlink: true